project:
  type: website

format:
  html:
    theme: cosmo
    css: metadata/styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating

metadata-files: [metadata/notebook.yml]
